#include <core.p4>
#include <v1model.p4>

const bit<16> TYPE_IPV4 = 0x800;
const bit<8>  TYPE_TCP  = 6;
const bit<8>  TYPE_UDP  = 17;
const bit<8>  TYPE_DNS  = 12;

#define BLOOM_FILTER_ENTRIES 4096
#define BLOOM_FILTER_BIT_WIDTH 1

/*************************************************************************
*********************** H E A D E R S  ***********************************
*************************************************************************/

typedef bit<9>  egressSpec_t;
typedef bit<48> macAddr_t;
typedef bit<32> ip4Addr_t;

header ethernet_t {
    macAddr_t dstAddr;
    macAddr_t srcAddr;
    bit<16>   etherType;
}

header ipv4_t {
    bit<4>    version;
    bit<4>    ihl;
    bit<8>    diffserv;
    bit<16>   totalLen;
    bit<16>   identification;
    bit<3>    flags;
    bit<13>   fragOffset;
    bit<8>    ttl;
    bit<8>    protocol;
    bit<16>   hdrChecksum;
    ip4Addr_t srcAddr;
    ip4Addr_t dstAddr;
}

header tcp_t{
    bit<16> srcPort;
    bit<16> dstPort;
    bit<32> seqNo;
    bit<32> ackNo;
    bit<4>  dataOffset;
    bit<4>  res;
    bit<1>  cwr;
    bit<1>  ece;
    bit<1>  urg;
    bit<1>  ack;
    bit<1>  psh;
    bit<1>  rst;
    bit<1>  syn;
    bit<1>  fin;
    bit<16> window;
    bit<16> checksum;
    bit<16> urgentPtr;
}

header udp_t {
    bit<16> srcPort;
    bit<16> dstPort;
    bit<16> length;
    bit<16> checksum;
}

header dns_t {
    bit<16> id;
    bit<1> qr;
    bit<3> opcode;
    bit<1> aa;
    bit<1> tc;
    bit<1> rd;
    bit<1> ra;
    bit<1> z;
    bit<4> rcode;
    bit<16> qdCount;
    bit<16> anCount;
    bit<16> nsCount;
    bit<16> arCount;
}

struct metadata {
    bit<1> dns_monitor;
    bit<1> dns_counter;
    bit<1> dns_tracker;
    bit<1> dns_counter_valid;
    bit<1> dns_tracker_valid;
    bit<1> dns_counter_reset;
    bit<1> dns_tracker_reset;
    bit<1> dns_counter_reset_valid;
    bit<1> dns_tracker_reset_valid;
    bit<1> dns_counter_reset_invalid;
    bit<1> dns_tracker_reset_invalid;
    bit<1> dns_counter_reset_invalid_valid;
    bit<1> dns_tracker_reset_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid;
    bit<1> dns_counter_reset_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_invalid_valid;
    bit<1> dns_tracker_reset_invalid_invalid_invalid_